---
apiVersion: v1
kind: CollectJob
metadata:
  name: test
spec:
  collectors:
    - id: kind
      terraform:
        provider: hashicorp/kubernetes
        args:
          config_path: ~/.kube/config
          config_context: kind-kind
    - id: api
      http:
        base_url: https://jsonplaceholder.typicode.com
  steps:
    - id: deployments
      collector: kind
      terraform_datasource:
        name: kubernetes_resources
        args:
          api_version: apps/v1
          kind: Deployment
          namespace: kube-system
    - id: users
      collector: api
      http_get:
        path: /users
        response_type: json
    - id: static
      static:
        filepath: ./job.yaml
        parse_as: raw
    - id: bar
      static:
        value: |
          {"foo": "${JOB_NAME}"}
        parse_as: json
    - id: helm
      exec:
        program: ["helm", "list", "--all-namespaces", "--output", "json"]
        format: json
  output:
    encoding:
      json:
        indent: "  "
    # archive:
    #   format: tar
    #   compression: gzip
    sink:
      filesystem:
        path: ./output
        prefix: ${JOB_NAME}/${JOB_DATE_RFC3339}
